[phases.setup]
nixPkgs = ["nodejs_20", "npm-10_x"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "npm run build",
  "mkdir -p .next/standalone/.next",
  "cp -r .next/static .next/standalone/.next/static"
]

[start]
cmd = "node .next/standalone/server.js"
