[phases.setup]
nixPkgs = ["nodejs_20", "npm-10_x"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "cp -r /app/.next/static /app/.next/standalone/.next/static && HOSTNAME=0.0.0.0 node /app/.next/standalone/server.js"
